---
stages:
    - name: "lint"

language: python

python:
    - "3.6"
    - "3.8"

# --------------------------------------------------------------------------
# Linting
# --------------------------------------------------------------------------

jobs:
    include:
        - stage: "lint"
          install:
            - pip install -r requirements-dev.txt
            - pip install .
          script:
            # - pytest
            - tox
