---
stages:
    - name: "lint"
    - name: "test"

language: python

python:
    - "3.6"
    - "3.8"

before_install:
  - pip install -r requirements.txt
  - pip install .

# --------------------------------------------------------------------------
# Linting
# --------------------------------------------------------------------------

jobs:
    include:
        - stage: "lint"
          script:
            - tox
        - stage: "test"
          script:
            - pytest
