---
stages:
    - name: "lint"
    - name: "test"

language: generic

python:
    - "3.6"

before_install:
    - pip install -r requirements.txt

# --------------------------------------------------------------------------
# Linting
# --------------------------------------------------------------------------

jobs:
    include:
        - stage: "lint"
          install: 
            - pip install tox-travis
          script:
            - tox
        - stage: "pytest"
          script:
            - pytest
